- job:
    name: bandit-integration-barbican
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-barbican/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/barbican
      - openstack/requirements

- job:
    name: bandit-integration-glance
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-glance/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/glance
      - openstack/requirements

- job:
    name: bandit-integration-glance_store
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-glance_store/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/glance
      - openstack/glance_store
      - openstack/requirements

- job:
    name: bandit-integration-keystone
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-keystone/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/keystone
      - openstack/requirements

- job:
    name: bandit-integration-keystonemiddleware
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-keystonemiddleware/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/keystone
      - openstack/keystonemiddleware
      - openstack/requirements

- job:
    name: bandit-integration-magnum
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-magnum/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/magnum
      - openstack/requirements

- job:
    name: bandit-integration-oslo.config
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-oslo.config/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/oslo.config
      - openstack/requirements

- job:
    name: bandit-integration-oslo.log
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-oslo.log/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/oslo.log
      - openstack/requirements

- job:
    name: bandit-integration-oslo.service
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-oslo.service/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/oslo.service
      - openstack/requirements

- job:
    name: bandit-integration-oslo.utils
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-oslo.utils/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/oslo.utils
      - openstack/requirements

- job:
    name: bandit-integration-oslo.vmware
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-oslo.vmware/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/oslo.vmware
      - openstack/requirements

- job:
    name: bandit-integration-python-keystoneclient
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-python-keystoneclient/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/keystone
      - openstack/python-keystoneclient
      - openstack/requirements

- job:
    name: bandit-integration-python-magnumclient
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-python-magnumclient/run.yaml
    timeout: 1800
    required-projects:
      - openstack/bandit
      - openstack/magnum
      - openstack/python-magnumclient
      - openstack/requirements

- job:
    name: bandit-integration-sahara
    parent: legacy-base
    run: playbooks/legacy/bandit-integration-sahara/run.yaml
    timeout: 1800
    required-projects:
      - openstack/ara
      - openstack/bandit
      - openstack/requirements
      - openstack/sahara

- project:
    name: openstack/bandit
    check:
      jobs:
        - bandit-integration-barbican
        - bandit-integration-glance
        - bandit-integration-keystone
        - bandit-integration-glance_store
        - bandit-integration-keystonemiddleware
        - bandit-integration-magnum
        - bandit-integration-oslo.config
        - bandit-integration-oslo.log
        - bandit-integration-oslo.service
        - bandit-integration-oslo.utils
        - bandit-integration-oslo.vmware
        - bandit-integration-python-keystoneclient
        - bandit-integration-python-magnumclient
        - bandit-integration-sahara
    gate:
      jobs:
        - bandit-integration-barbican
        - bandit-integration-glance
        - bandit-integration-keystone
        - bandit-integration-glance_store
        - bandit-integration-keystonemiddleware
        - bandit-integration-magnum
        - bandit-integration-oslo.config
        - bandit-integration-oslo.log
        - bandit-integration-oslo.service
        - bandit-integration-oslo.utils
        - bandit-integration-oslo.vmware
        - bandit-integration-python-keystoneclient
        - bandit-integration-python-magnumclient
